ticker_lists = [
    'BTC', 'SAND', 'DGB', 'YGG', 'EGLD', 'GALA', 'T', 'AXS', 'CTK',
    'SPELL', 'EOS', 'AGIX', 'DYDX', 'REN', 'APE', 'CHR', 'FLM', 'LDO',
    'ZIL', 'OMG', 'SOL', 'LINA', 'SFP', 'PEOPLE', 'VET', 'BAKE',
    'MINA', 'STORJ', 'HIGH', 'RSR', 'YFI', 'MAGIC', 'IDEX', 'LQTY',
    'DOT', 'ASTR', 'XEM', 'UMA', 'IOTA', 'LINK', 'ALICE', 'WOO', 'ETC',
    'DUSK', 'SKL', 'ENJ', 'HOOK', 'ARKM', 'NKN', 'XVG', 'HOT', 'LEVER',
    'MDT', 'ZEC', 'KAVA', 'PHB', 'OCEAN', 'TOMO', 'ICX', 'FET',
    'MATIC', 'BAL', 'IOST', 'THETA', 'XRP', 'RAD', 'CELO', 'API3',
    'DOGE', 'AVAX', 'HFT', 'ZRX', 'CFX', 'ARB', 'WAVES', 'UNFI', 'LRC',
    'TRB', 'SSV', 'IOTX', 'MASK', 'ARPA', 'ANT', 'HBAR', 'SNX', 'ENS',
    'SUSHI', 'STX', '1INCH', 'ATOM', 'GRT', 'AMB', 'ALGO', 'IMX',
    'BAND', 'RNDR', 'FLOW', 'BCH', 'NEO', 'REEF', 'AR', 'DAR', 'BEL',
    'DASH', 'MKR', 'DENT', 'ATA', 'C98', 'GMT', 'LTC', 'INJ', 'RDNT',
    'OP', 'ZEN', 'GMX', 'JOE', 'QNT', 'COMBO', 'BNX', 'WLD', 'XVS',
    'KSM', 'SXP', 'CRV', 'AGLD', 'XLM', 'CYBER', 'CVX', 'FIL', 'RLC',
    'ALPHA', 'AAVE', 'OXT', 'RUNE', 'ANKR', 'KEY', 'XTZ', 'MANA',
    'QTUM', 'PENDLE', 'XMR', 'COMP', 'ONE', 'KNC', 'CHZ', 'EDU',
    'CELR', 'TLM', 'ONT', 'GAL', 'LIT', 'UNI', 'JASMY', 'CKB', 'SEI',
    'ETH', 'BLZ', 'CTSI', 'MAV', 'OGN', 'MTL', 'LPT', 'FXS', 'RVN',
    'PERP', 'NMR', 'COTI', 'APT', 'ID', 'BNB', 'FTM', 'AUDIO', 'TRX',
    'GTC', 'BAT', 'BNT', 'ACH', 'STG', 'SUI', 'ICP', 'STMX', 'KLAY',
    'TRU', 'ADA', 'ROSE', 'NEAR',
]
